project:
  type: manuscript
  render:
    - "!AGENTS.md"
    - "!meta/"
    - "**/*.qmd"

manuscript:
  article: index.qmd

bibliography: references.bib

format:
  html: default

execute:
  freeze: true



